### ISSUE TITLE
Needs an update again. Only loading 1 ruleset with an unhandled exception on latest version of lazer.

### ISSUE THREAD

**Issue by TheFantasticLoki** [Flutterish/rurusetto-addon#6] opened 2022-07-28 22:10 UTC
Title says all. Needs an update for the latest game version to fix an error.

**Comment by Flutterish** [comment] 2022-07-28 23:24
Will do sometime tomorrow. Is there any specific code it throws?

**Comment by Flutterish** [comment] 2022-07-30 17:00
I am not getting any errors with the current release, could you elaborate what exactly is happening?

**Comment by Loreos7** [comment] 2022-07-30 17:25
He might meant solosu ruleset
![image](https://user-images.githubusercontent.com/86934170/181934758-ef470787-80a5-437b-8fc1-8e9e14dd87a4.png)

**Comment by Loreos7** [comment] 2022-07-30 17:26
Moreover after loading solosu rurusetto listing looks like this
![image](https://user-images.githubusercontent.com/86934170/181934811-428e8b62-e490-4a70-90b0-47eab97c387c.png)

**Comment by Flutterish** [comment] 2022-07-30 18:04
I see. The error is caused by the ruleset not using the new texture store. I will need to update both solosu and ruru to avoid this in the future.

**Comment by Flutterish** [comment] 2022-07-30 18:16
This is now fixed, a patch for solosu will be released soon.

**Closed by Flutterish** 2022-07-30 18:16 UTC
